services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webreconx_php
    volumes:
      - ./:/var/www
    expose:
      - "9000"
    networks:
      - internal_network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webreconx_worker
    depends_on:
      - php
    volumes:
      - ./:/var/www
    networks:
      - internal_network
    environment:
      - EXECUTE_QUEUE_WORK=true

  nginx:
    image: nginx:alpine
    container_name: webreconx_nginx
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - internal_network

  mysql:
    image: mysql:8.0
    container_name: webreconx_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=webreconx
    volumes:
      - ./docker/db/volumes:/var/lib/mysql
      - ./docker/db/init:/docker-entrypoint-initdb.d
    networks:
      - internal_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: webreconx_php_my_admin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql
    networks:
      - internal_network

  mongo:
    image: mongo:latest
    container_name: webreconx_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo/data:/data/db
      - ./docker/mongo/config:/data/configdb
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge